spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgeSLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: frankmascco@gmail.com
    password: arsq owcm vhdb gtzk
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
application:

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://192.168.18.197:8088,http://192.168.18.197:8080
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
